### ISSUE TITLE
Ineffecient Code

### ISSUE THREAD

**Issue by pranshuagarwal7** [manishsingh10895/competitive-programming#1]
The left rotation can be done in O(n) time complexity.Try to optimise the solution.

**Comment by manishsingh10895** [comment]
This was the most efficient one I could find, both time and space wise, If you have a better method, please put forward.

**Comment by pranshuagarwal7** [comment]
Let us say x=size-order.Left rotation is done using the logic of reverse in O(n) time. First reverse the array from 0 to x-1 then reverse x to size-1 and then from 0 to size-1. and the array is left rotated. Just need two arguments for rotate function and for reverse need three.

**Comment by manishsingh10895** [comment]
This too would take O(n) time
